### ISSUE TITLE
 module requires Go 1.13

### ISSUE THREAD

**Issue by ytwig** [ugorji/go-codec#288]
Latest commit seems to break things.
Trying to build a project based of GIN router that has dependency on go-codec, and getting this error `go build github.com/ugorji/go/codec: module requires Go 1.13`

Any suggestions?

**Comment by ugorji** [comment]
@ytwig 

I need a reproducer:

- what did you do?
- what did you expect to see?
- what did you see?

This way, I can reproduce it here and try to help.

**Comment by ugorji** [comment]
Please try again. 

The go command, behind the scenes, updates the go.mod file to specify a release version. Now removed.

**Comment by ytwig** [comment]
The latest commit added the go.mod file with a dependency "go 1.13".
When you try to build a simple project that imports "github.com/ugorji/go/codec", it fails

For example

`package main

import(
	"fmt"
	"github.com/ugorji/go/codec"
)


func main(){
	decode := codec.Decoder{}
	fmt.Print(decode)
}
`

**Comment by ytwig** [comment]
Thanks :)

**Comment by ugorji** [comment]
@ytwig please let me know if that works.

**Comment by ytwig** [comment]
@ugorji still fails.
You need to update/make new release
(technically i can set the latest commit as the release, but would be better to just have it in a release)

**Comment by ugorji** [comment]
Please try again with 1.1.4

**Comment by ytwig** [comment]
Works :)
Thanks
