### ISSUE TITLE
go-get error

### ISSUE THREAD

**Issue by aaronjheng** [ugorji/go-codec#289]
When using go-get in module mode, I got this error:

	go: finding github.com/ugorji/go/codec latest
	package github.com/ugorji/go/codec: unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
		github.com/ugorji/go v1.1.4 (/Users/aaron/.go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
		github.com/ugorji/go/codec v0.0.0-20190320090025-2dc34c0b8780 (/Users/aaron/.go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20190320090025-2dc34c0b8780)

**Comment by ugorji** [comment]
Do you have a go.mod inside your codec folder?

Previously, go.mod was in codec, and we now moved it to the top-level folder. Check to ensure that you do not have leftover files.

I know a clean go get works, so it might be something messed up in your local machine state.

You may have to read up on module usage to clean up your state.

Let me know how it goes.

**Comment by aaronjheng** [comment]
This is part of my go.mod file:

	require (
		github.com/coreos/etcd v3.3.12+incompatible // indirect
		github.com/go-chi/chi v4.0.2+incompatible
		github.com/go-redis/redis v6.15.2+incompatible
		github.com/golang/protobuf v1.3.1 // indirect
		github.com/inconshreveable/mousetrap v1.0.0 // indirect
		github.com/konsorten/go-windows-terminal-sequences v1.0.2 // indirect
		github.com/kr/pretty v0.1.0 // indirect
		github.com/kr/pty v1.1.4 // indirect
		github.com/onsi/ginkgo v1.8.0 // indirect
		github.com/onsi/gomega v1.5.0 // indirect
		github.com/pelletier/go-toml v1.3.0 // indirect
		github.com/sirupsen/logrus v1.4.1
		github.com/spf13/afero v1.2.2 // indirect
		github.com/spf13/cobra v0.0.3
		github.com/spf13/jwalterweatherman v1.1.0 // indirect
		github.com/spf13/viper v1.3.2
		github.com/stretchr/testify v1.3.0 // indirect
		github.com/ugorji/go v1.1.4 // indirect
		github.com/ugorji/go/codec v0.0.0-20190320090025-2dc34c0b8780 // indirect
		go.uber.org/dig v1.7.0
		golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5 // indirect
		golang.org/x/net v0.0.0-20190404232315-eb5bcb51f2a3 // indirect
		golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6 // indirect
		golang.org/x/sys v0.0.0-20190405154228-4b34438f7a67 // indirect
		gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127 // indirect
	)

As you can see, there are two entries of go-codec which come from viper. There is a related [issue](https://github.com/spf13/viper/issues/633) and a possible [solution](https://github.com/golang/go/issues/29332#issuecomment-448669442) I guess.
Right now, I don't know why.

**Comment by ugorji** [comment]
So. Can't you take one of them out? What happens when you do?v

**Comment by aaronjheng** [comment]
Here is a demo go.mod.

	module go.example.com/tools

	require (
		github.com/spf13/viper v1.3.2
	)

When I ran `go get -v -u github.com/ugorji/go/codec`, I got this error:

	package github.com/ugorji/go/codec: unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
			github.com/ugorji/go v1.1.4 (C:\Users\aaron\.go\pkg\mod\github.com\ugorji\go@v1.1.4\codec)
			github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8 (C:\Users\aaron\.go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181204163529-d75b2dcb6bc8)

**Comment by ugorji** [comment]
I still don't know how to help you.

There is something funny going on with your conflicting use of modules that I do not know how to resolve.

C:\Users\aaron\.go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181204163529-d75b2dcb6bc8 is the messed up part. go-codec as at 1.1.4 works well. It seems someone else is using a non-module enabled version of go-codec, and I really do not know all the ideosynchracies of go modules yet.

Eventually, you have duplicate "github.com/ugorji/go/codec" in your go.mod that is causing a problem. I don't see how this is go-codec's fault. go-codec is just making itself module enabled. You use of modules is messing things up somewhere.

I wish I could help. But I am the wrong person to get help here. You will have to do some troubleshooting on your own.

I would try using a release version of go, and tip. If one of them works, then you can decide where to file an issue or how to proceed.

**Comment by aaronjheng** [comment]
> `C:\Users\aaron.go\pkg\mod\github.com\ugorji\go\codec@v0.0.0-20181204163529-d75b2dcb6bc8 is the messed up part. go-codec as at 1.1.4 works well. It seems someone else is using a non-module enabled version of go-codec, and I really do not know all the ideosynchracies of go modules yet.`
It's from viper's [go.mod](https://github.com/spf13/viper/blob/master/go.mod) file. Maybe I should do something else to avoid this.
Many thanks. :)

**Comment by iamsee** [comment]
github.com/gin-contrib/cors same error

**Comment by aaronjheng** [comment]
@ugorji I noticed you changed the import path back. The problem I had is gone. May be it's better to create a new repo named go-codec and leave this repo as it is. Just an immature thought. :)

**Comment by ugorji** [comment]
@aaronjheng Thanks so much for this comment. This is the last proof I need to leave well enough alone and not change the repo name as was suggested in https://github.com/ugorji/go/issues/43#issuecomment-483001108
